# -*- coding: utf-8 -*-
"""PE_25OCT_25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JXzLGmnZd664_nDloDFjxpKbA9G7f7O1
"""

# Prompt Engineering

# 1. Prompt in Python -> LLM [another server for openai/gemini] -> Output

# Have a simple code to get the output from llm
# Small usecase and prompt engineering is really important
!pip install google-generativeai

import google.generativeai as genai

# Configure with your key
genai.configure(api_key="")

# https://aistudio.google.com/prompts/new_chat
# get api_key > create_api_key

# Choose model: gemini-1.5-flash or gemini-1.5-pro
model = genai.GenerativeModel("gemma-3-1b-it")

# Make a prompt call
response = model.generate_content("Write a short poem about Diwali")

# Print the response
print(response.text)

# how to maintain consitency of response
#

# Iphone has the best camera and features where as Samsung offers value pricing
# Positive

# Please write a prompt, where it can give you the sentiment analysis for a review

# where as Samsung offers value pricing

# IBM is great company - Positive sentiment
# IBM is bad company - Negative sentiment
# i heard about IBM  - Neutral sentiment
#

# Choose model: gemini-1.5-flash or gemini-1.5-pro
model = genai.GenerativeModel("gemma-3-1b-it")

# Make a prompt call
response = model.generate_content("Please provide the sentiment analysis for this review. Iphone has the best camera and features")

# Print the response
print(response.text)

# Choose model: gemini-1.5-flash or gemini-1.5-pro
model = genai.GenerativeModel("gemma-3-1b-it")

# Make a prompt call
response = model.generate_content("you are sentiment analyzer. your task is to analyze the given statements for positive, negative and neutral. Iphone has the best camera and features")
# system prompt:
#
# Print the response
print(response.text)

prompt = '''You are a Precise Sentiment Classifier for short product/company reviews.
TASK
- Classify the overall sentiment of a single review as exactly one of:
  ["positive", "negative", "neutral"].
- Return JSON ONLY, no extra text.
- Include a calibrated confidence score in [0,1] and brief evidence.
- If the text is opinion-free (facts, questions, hearsay) → "neutral".
- If mixed sentiment, choose the dominant sentiment and set "mixed": true.
DEFINITIONS
- positive: clear praise, satisfaction, recommendation, or favorable comparison.
- negative: complaint, dissatisfaction, defect, bug, rejection, or unfavorable comparison.
- neutral: factual statements, questions, news/hearsay, feature listing without judgment, unclear polarity.
Iphone has the best camera and features
'''
prompt ='''Give a sentiment review for this, only give 1 word anwer.positive negative neutral only: Iphone has the best cameras and features'''


# Iphone has the best camera and features where as Samsung offers value pricing

# Iphone has the facial recognition, which works very nice and quality is awesome

# This phone battery drains faster leaving me annoyed and i recently bought this, i had a good experience with anothre brand like Iphone

# for iphone, sentiment: positive
# topics: camera, features
# samsung, sentiment: Positive
# topics: value_pricing


# Choose model: gemini-1.5-flash or gemini-1.5-pro
model = genai.GenerativeModel("gemma-3-1b-it")

# Make a prompt call
response = model.generate_content(prompt)
# system prompt:
#
# Print the response
print(response.text)

prompt = '''You are a Precise Multi-bramd Sentiment and Topic Classifier.
TASK
- Analyze the given review text.
- Identify each entity (brand/product/service) mentioned.
- Determine the sentiment (positive, negative, or neutral) expressed for each entity.
- Identify topics or aspects discussed (e.g., camera, features, pricing, quality, etc.).
- Return the results strictly in JSON format.
GUIDELINES
- Each entity must have its own sentiment and topics.
- Ignore filler text that does not convey opinion.
- If sentiment is mixed, choose the dominant tone and mark "mixed": true.
- If no sentiment is expressed, classify it as "neutral".
- Maintain consistent lowercase keys and values.
Iphone has the best camera and features where as Samsung offers value pricing
output formt : in JSON'''

prompt ='''Analyze the sentiment from the reviews, and mention the topics being discussed, in the following format
sentiment: ___
topics: ___
Iphone has the best camera and features where as Samsung offers value pricing
'''

prompt ='''Being a Sentiment Analyst, consider the following prompt and provide analysis based iphone and samsung also consider the various features of the both phones.
Iphone has the best camera and features where as Samsung offers value pricing
'''

prompt ='''You are a mobile phone analysis prompt. Please analyze a given statement and provide your output in 'Phone Name', 'Feature', 'Topics', 'Sentiment'.'''
# Choose model: gemini-1.5-flash or gemini-1.5-pro
model = genai.GenerativeModel("gemma-3-1b-it")

# Make a prompt call
response = model.generate_content(prompt)
# system prompt:
#
# Print the response
print(response.text)

# Input: Text data - review
# Output: sentiment by brand, topics by brand
# JSON format

prompt = '''Your task is to analyze the given review text.
- Identify each entity (brand/product/service) mentioned.
- Determine the sentiment (positive, negative, or neutral) expressed for each entity.
- Identify topics or aspects discussed (e.g., camera, features, pricing, quality, etc)
- Return the results strictly in JSON format.
Iphone has the best camera and features where as Samsung offers value pricing'''
model = genai.GenerativeModel("gemma-3-1b-it")

# Make a prompt call
response = model.generate_content(prompt)
# system prompt:
#
# Print the response
print(response.text)

# '''Iphone has the best camera but bad features where as Samsung offers value pricing'''

#"Samsung’s zoom is a huge selling point and pricing is good, Iphone has better pixels"
# output:
# iphone - camera - positive
# iphone - features - negative
# samsung - pricing - positive

# zero shot prompting:
# few shot prompting: 15% better responses

prompt = '''You are an expert in text analysis.
Task: Classify sentiment for each brand and for each topic correspoding to the brand.
Text: Samsung zoom is a huge selling point and pricing is good, Iphone has better pixels
Output: {"Samsung": {"zoom": "positive", "pricing": "positive"},
 "Iphone": {"camera": "positive", "pixels": "positive"}}
Text: Iphone has the best camera but bad features. Samsung offers better service
'''

model = genai.GenerativeModel("gemma-3-1b-it")

# Make a prompt call
response = model.generate_content(prompt)
# system prompt:
#
# Print the response
print(response.text)

prompt = '''Think step by step. You are an expert in reasoning.
Text: I have 3 apples in a day, they can get multiplied three times if i eat my breakfast and my son has 2 bananas, they become four times if he goes to school and he eats one among them in school.
Given that i had eat idly in my breakfast and my son went to school, How many fruits are left.
Output: 16 fruits
Text: I have 6 apples in a day, they can get multiplied three times if i eat my breakfast and my son has 6 bananas, they become four times if he goes to school and he eats one among them in school.
Given that i had eat idly in my breakfast and my son went to school, How many fruits are left.
Output:'''
# chain of thought -
# gpt-4o [reasoning]
# 3*3+4*2=17-1=16


prompt = 'provide latest usa stock martket news, output json  by stock'
model = genai.GenerativeModel("gemma-3-1b-it")

# Make a prompt call
response = model.generate_content(prompt)
# system prompt:
#
# Print the response
print(response.text)


## prompting:

# system Prompt:
# User Prompt: input
# Output format:

## Keep it simple
## Use rules when necessary
## Good few shot examples
## pick the right prompting strategy- zero shot, few shot, chain of thought,

## LLM settings

## How to minimize AI hallucinations with longer prompts.. whats the catch there?

## question -> sql query
## 500-1000

##

import requests
text = requests.get('https://finance.yahoo.com/news/')

import requests

# Yahoo Top News RSS feed
url = "https://news.yahoo.com/rss/"

response = requests.get(url)

response

## Predictive models:
## ml
## dl
## genai

## Generative models:
## AUTOENCODERS - Data -> encode -> decode - reconstruct input [2016]
## 784 - 32 [encode] - 784 [decode] reconstruction[loss]
## PE -> LLM [] -> OUTPUT
## input -> encode -> decode -> output
## GAN -
## Bayesian models -> kitchen occuring with cricket? 100 sentences
# kitchen occuring with cooking? 100000 sentences


## LLM Settings

## Temperature: 0 to 1 or 2
## a temperature 0 means deterministic, high temperature means creative
## Sun rises in the east ___
# high temperature
## Sun rises in the __ [east [0.43], west[0.21], north[0.12], south, up, sky, other[0.001]]
# top_p: 0.6 [east, west]
# top_k: 7 [east, west, north, south, up, sky, other]

# code completion - python code, java code - low temperature
## low temperature:
## high temperature:

# patent writing | social media | story writing:
## low temperature:
## high temperature:


# top_p: ranges between 0 to 1
# top_p: diverse responses, increase to a higher value

# Max Length: number of words to output:
#top_k:

# stop_sequences: "."

# Step 2: Define generation config
generation_config = {
    "temperature": 1,        # Creativity level (0 = deterministic, 1 = creative)
    "top_p": 0.01,             # Nucleus sampling
    # "top_k": 40,               # Limits sampling to top K tokens
    "max_output_tokens": 1024,  # Limit response length
    "response_mime_type": "text/plain",  # Can also be 'application/json'
}

# Step 3: Create the model
model = genai.GenerativeModel(
    model_name="gemma-3-1b-it",
    generation_config=generation_config,
)

# model = genai.GenerativeModel("gemma-3-1b-it")

# Make a prompt call
response = model.generate_content('''Generate things.
Generate new text audio video… creative and innovative
generate results
Generative AI generates something like text, image or video
Generating things like text,image, code based on the data it has available and prompt.
Gen AI means — Generate audio, speech, image, text etc through algorithms by taking input as data
AI used to build things.
Ask anything and generate the answer
Generate Information as per user need
''')
# system prompt:
#
# Print the response
print(response.text)

## Prompt:
## LLM Settings: temp. top_p, top_k, stop_seque, max_tokens

# zero shot prompting
#